# Generated by Django 5.2.14 on 2026-05-31 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaObservedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'insta_observed_user',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='InstaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('story', 'Story'), ('post', 'Post')], max_length=20)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=20)),
                ('file_name', models.CharField(max_length=500)),
                ('url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='insta_monitor.instaobserveduser')),
            ],
            options={
                'db_table': 'insta_content',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('observed_user', 'content_type', 'media_type', 'file_name'), name='unique_insta_content_item')],
            },
        ),
    ]
