# Generated by Django 5.2.14 on 2026-05-31 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=500)),
                ('query_url', models.TextField()),
                ('source', models.CharField(blank=True, choices=[('olx', 'OLX'), ('rieltor', 'Rieltor')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_telegram_id', on_delete=django.db.models.deletion.CASCADE, related_name='checker_queries', to='telegram_users.telegramuser')),
            ],
            options={
                'db_table': 'checker_query',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoundAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_url', models.TextField()),
                ('ad_description', models.TextField(blank=True)),
                ('ad_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(db_column='query_id', on_delete=django.db.models.deletion.CASCADE, related_name='found_ads', to='monitors.checkerquery')),
            ],
            options={
                'db_table': 'found_ad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='checkerquery',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'query_url'), name='unique_active_query_url_per_user'),
        ),
        migrations.AddConstraint(
            model_name='foundad',
            constraint=models.UniqueConstraint(fields=('query', 'ad_url'), name='unique_ad_url_per_query'),
        ),
    ]
