# Generated by Django 5.2.14 on 2026-05-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('source', models.CharField(choices=[('celery', 'Celery'), ('telegram', 'Telegram'), ('web', 'Web'), ('api', 'API'), ('scraper', 'Scraper'), ('system', 'System')], default='system', max_length=20)),
                ('logger_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('job_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'job_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
